plot:
  kinetics:
    figure_size:
    - 7
    - 5
    legend_location: lower right
    model: true
    skip_header: 1
    title: null
    use_cols:
    - 0
    - 1
    xcolumn: Time (min)
    xlabel: Time (min)
    xlimit: null
    ycolumn: Abs
    ylabel: Absorbance (A.U.)
    ylimit: null
  spectrum:
    figure_size:
    - 7
    - 5
    legend_location: upper left
    skip_header: 1
    title: null
    use_cols:
    - 0
    - 1
    xcolumn: Wavelength (nm)
    xlabel: Wavelength (nm)
    xlimit:
    - 300
    - 500
    ycolumn: Abs
    ylabel: Absorbance (A.U.)
    ylimit: null
